In [68]:
import pandas as pd
from openai import OpenAI
from sklearn.model_selection import train_test_split
import os
from dotenv import load_dotenv

load_dotenv(".env", override=True)

True

In [69]:
df = pd.read_excel("data/data.xlsx") # reading data
df.head()

,input_text,model_name,parameter_count,dataset_size_gb,sequence_length,batch_size,training_method,precision,number_of_layers,hidden_size,epochs,training_time_constraint_hours,workload_type
0,I want to fine-tune Llama 7B with LoRA on a 3...,Llama 7B,7B,30.0,2048.0,NaN,LoRA,NaN,NaN,NaN,NaN,NaN,training
1,I want to fine-tune Llama 3.2 3B using LoRA o...,Llama 3.2 3B,3B,50.0,2048.0,8.0,LoRA,BF16,NaN,NaN,3.0,NaN,training
2,I want to run inference on Llama 3 70B,Llama 3 70B,70B,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,inference
3,Please instruction-tune Llama 3.1 8B with LoRA...,Llama 3.1 8B,8B,12.0,4096.0,2.0,LoRA,BF16,NaN,NaN,2.0,12,training
4,I need QLoRA supervised fine-tuning of Mistral...,Mistral 7B,7B,8.0,2048.0,4.0,QLoRA,BF16,NaN,NaN,3.0,10,training

In [70]:
df.describe()

,dataset_size_gb,sequence_length,batch_size,number_of_layers,hidden_size,epochs
count,43.000000,55.000000,51.000000,3.000000,3.000000,39.000000
mean,15.664506,2681.018182,5.666667,20.000000,1621.333333,2.115385
std,23.966658,1910.561402,6.348753,6.928203,532.906496,0.969682
min,0.250000,512.000000,0.000000,12.000000,1024.000000,0.500000
25%,4.000000,2048.000000,2.000000,18.000000,1408.000000,1.500000
50%,6.000000,2048.000000,4.000000,24.000000,1792.000000,2.000000
75%,13.500000,4096.000000,8.000000,24.000000,1920.000000,3.000000
max,100.000000,8192.000000,32.000000,24.000000,2048.000000,5.000000

In [71]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 60 entries, 0 to 59
Data columns (total 13 columns):
 #   Column                          Non-Null Count  Dtype
---  ------                          --------------  -----
 0   input_text                      60 non-null     object
 1   model_name                      58 non-null     object
 2   parameter_count                 56 non-null     object
 3   dataset_size_gb                 43 non-null     float64
 4   sequence_length                 55 non-null     float64
 5   batch_size                      51 non-null     float64
 6   training_method                 43 non-null     object
 7   precision                       52 non-null     object
 8   number_of_layers                3 non-null      float64
 9   hidden_size                     3 non-null      float64
 10  epochs                          39 non-null     float64
 11  training_time_constraint_hours  20 non-null     object
 12  workload_type                   60 non-null     object
dtypes: float64(6), object(7)
memory usage: 6.2+ KB