In [1]:
import pandas as pd

In [ ]:
df = pd.read_excel("data/data.xlsx") # reading data
df.head()

,input_text,model_name,parameter_count,dataset_size_gb,sequence_length,batch_size,training_method,precision,epochs
0,I want to fine-tune Llama 7B with LoRA on a 30...,Llama 7B,7B,30,2048,NaN,LoRA,NaN,NaN
1,I want to fine-tune Llama 3.2 3B using LoRA on...,Llama 3.2 3B,3B,50,2048,8.0,LoRA,BF16,3.0

In [6]:
df.describe()

       dataset_size_gb  sequence_length  batch_size  epochs
count         2.000000              2.0         1.0     1.0
mean         40.000000           2048.0         8.0     3.0
std          14.142136              0.0         NaN     NaN
min          30.000000           2048.0         8.0     3.0
25%          35.000000           2048.0         8.0     3.0
50%          40.000000           2048.0         8.0     3.0
75%          45.000000           2048.0         8.0     3.0
max          50.000000           2048.0         8.0     3.0

In [7]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2 entries, 0 to 1
Data columns (total 9 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   input_text       2 non-null      object
 1   model_name       2 non-null      object
 2   parameter_count  2 non-null      object
 3   dataset_size_gb  2 non-null      int64
 4   sequence_length  2 non-null      int64
 5   batch_size       1 non-null      float64
 6   training_method  2 non-null      object
 7   precision        1 non-null      object
 8   epochs           1 non-null      float64
dtypes: float64(2), int64(2), object(5)
memory usage: 276.0+ bytes